// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Com.Costoda.ReferenceApp.Mac
{
	public partial class ADALConnectionViewController : NSViewController
	{
		public ADALConnectionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
