// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Com.Costoda.ReferenceApp.Mac
{
	public partial class GraphProjectMenuViewController : NSViewController
	{
		public const string IdentifierKey = "GraphProjectMenuViewController";

		public GraphProjectMenuViewController (IntPtr handle) 
			: base (handle)
		{
		}
	}
}
