// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Com.Costoda.ReferenceApp.Mac
{
	public partial class GraphGroupsMenuViewController : NSViewController
	{
		public const string IdentifierKey = "GraphGroupsMenuViewController";

		public GraphGroupsMenuViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
